### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ForeverWintr** [ForeverWintr/blueprints#3]
- [ ] Static frame examples
- [x] Plan visualization
  - [ ] Using Dash?
    - Using a web browser as a UI has some caveats, like knowing when to stop the server. [webui](https://webui.me/docs/#/python_api) looks interesting. 
- [ ] Factory API that supports distributed processing
  - This seems hard considering firewalls and such. 
- [x] set up mypy
- [x] Allow missing
    - For series recipes, missing fill value can be a constant recipe or series of fill value if there is an index. FrameRecipe can handle.
- [x] Dependency order. Args and kwargs? 
- [x] Blueprints. ~Hashable~? - Seems unlikely you'd build the same blueprint twice.
- [ ] Factory Caching
- [ ] Make installable
- [ ] Use in real code. Note: need python 3.10
- [x] Should the factory be able to produce missing as a final output (e.g., the return of `factory.process_recipe`)? That seems undesirable, but the user can decide whether to allow_missing on the final recipe, too. I'll say yes for now. 
- [ ] Downstream effects? Satisfy a missing data fill value if something is reindexed.
- [x] #9
- [ ] Exception Grouping
